### PR TITLE
Making project executable

### PR DESCRIPTION
**Pull request by mcadelago**
I wanted to use this in a different way than the project previously functioned. Here's how it works now with this PR:

To install: `npm install mddir -g`

To generate markdown for current directory: `mddir`

To generate for any absolute path: `mddir /absolute/path`

To generate for a relative path: `mddir ~/Documents/whatever`

The md file gets generated in your working directory instead of in the mddir project folder. Let me know what you think.

### CODE REVIEW

**Comment by mcadelago** [comment]
If you want to test this out, pull down the code and run `npm install . -g` from the root of the project directory. You won't be able to install using the project name until after you merge this code in

**Comment by JohnByrneRepo** [comment]
Hi @ex1machina, apologies for the late response and thanks for making this change - I'd been meaning to make this executable for added convenience.  Also, excellent solution to specifying absolute or relative paths.  I'll try this out asap then merge into master.

I'm also planning on an alternative display within the browser, as the main goal was to provide a user with a method of familiarising themselves with a project rather than generating markdown exclusively.  If I add this functionality, then I will generate the markup and any required JavaScript and css from node.

**Comment by rstoenescu** [comment]
:thumbsup: I just found this project and I would've made the same PR. Good job.

**Comment by Koleok** [comment]
@JohnByrneRepo Any plans to merge this? Would love to use mddir but it really needs this PR

**Comment by JohnByrneRepo** [comment]
Merged.  Definitely needed, and thanks for the additions.  I should also be adding better ignore list functionality at some point.  Thanks for the support :+1:

**Comment by Koleok** [comment]
Nice thanks @JohnByrneRepo

**Pull request merged**
